// Mocks generated by Mockito 5.0.16 from annotations
// in zc_desktop_flutter/test/helpers/test_helpers.dart.
// Do not manually edit this file.

import 'dart:async' as _i2;
import 'dart:io' as _i12;
import 'dart:ui' as _i20;

import 'package:dio/dio.dart' as _i3;
import 'package:dio_cache_interceptor/dio_cache_interceptor.dart' as _i4;
import 'package:flutter/material.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stacked_services/stacked_services.dart' as _i8;
import 'package:zc_desktop_flutter/model/app_models.dart' as _i5;
import 'package:zc_desktop_flutter/services/auth_service.dart' as _i6;
import 'package:zc_desktop_flutter/services/centrifuge_service.dart' as _i7;
import 'package:zc_desktop_flutter/services/channels_service.dart' as _i13;
import 'package:zc_desktop_flutter/services/dm_service.dart' as _i14;
import 'package:zc_desktop_flutter/services/local_storage_service.dart' as _i15;
import 'package:zc_desktop_flutter/services/organization_service.dart' as _i16;
import 'package:zc_desktop_flutter/services/recent_search_service.dart' as _i17;
import 'package:zc_desktop_flutter/services/startup_service.dart' as _i10;
import 'package:zc_desktop_flutter/services/user_service.dart' as _i18;
import 'package:zc_desktop_flutter/services/window_title_bar_service.dart'
    as _i19;
import 'package:zc_desktop_flutter/services/zuri_api/zuri_api_service.dart'
    as _i11;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeStreamController_0<T> extends _i1.Fake
    implements _i2.StreamController<T> {}

class _FakeDio_1 extends _i1.Fake implements _i3.Dio {}

class _FakeCacheOptions_2 extends _i1.Fake implements _i4.CacheOptions {}

class _FakeMember_3 extends _i1.Fake implements _i5.Member {}

class _FakeUser_4 extends _i1.Fake implements _i5.User {}

class _FakeUsers_5 extends _i1.Fake implements _i5.Users {}

class _FakeChannel_6 extends _i1.Fake implements _i5.Channel {}

class _FakeSendMessageResponse_7 extends _i1.Fake
    implements _i5.SendMessageResponse {}

class _FakeAuth_8 extends _i1.Fake implements _i5.Auth {}

class _FakeUserProfile_9 extends _i1.Fake implements _i5.UserProfile {}

class _FakeOrganization_10 extends _i1.Fake implements _i5.Organization {}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i6.AuthService {
  @override
  set auth(_i5.Auth? _auth) =>
      super.noSuchMethod(Invocation.setter(#auth, _auth),
          returnValueForMissingStub: null);
  @override
  _i2.Future<void> loginUser({String? email, String? password}) =>
      (super.noSuchMethod(
          Invocation.method(
              #loginUser, [], {#email: email, #password: password}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<void> signup(
          {String? password, String? email, String? fName, String? lName}) =>
      (super.noSuchMethod(
          Invocation.method(#signup, [], {
            #password: password,
            #email: email,
            #fName: fName,
            #lName: lName
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<void> confirmEmail(String? otpCode) =>
      (super.noSuchMethod(Invocation.method(#confirmEmail, [otpCode]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<void> requestPasswordResetCode(String? email) =>
      (super.noSuchMethod(Invocation.method(#requestPasswordResetCode, [email]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<void> verifyPasswordResetCode(String? resetCode) => (super
      .noSuchMethod(Invocation.method(#verifyPasswordResetCode, [resetCode]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<void> updateUserPassword(String? password) =>
      (super.noSuchMethod(Invocation.method(#updateUserPassword, [password]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  void logOut(String? token) =>
      super.noSuchMethod(Invocation.method(#logOut, [token]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CentrifugeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCentrifugeService extends _i1.Mock implements _i7.CentrifugeService {
  @override
  _i2.StreamController<String> get messageStreamController =>
      (super.noSuchMethod(Invocation.getter(#messageStreamController),
              returnValue: _FakeStreamController_0<String>())
          as _i2.StreamController<String>);
  @override
  set messageStreamController(
          _i2.StreamController<String>? _messageStreamController) =>
      super.noSuchMethod(
          Invocation.setter(#messageStreamController, _messageStreamController),
          returnValueForMissingStub: null);
  @override
  String get websocketUrl =>
      (super.noSuchMethod(Invocation.getter(#websocketUrl), returnValue: '')
          as String);
  @override
  _i2.Future<dynamic> connect() =>
      (super.noSuchMethod(Invocation.method(#connect, []),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  void disconnect() => super.noSuchMethod(Invocation.method(#disconnect, []),
      returnValueForMissingStub: null);
  @override
  _i2.Future<dynamic> subscribe(String? channel) =>
      (super.noSuchMethod(Invocation.method(#subscribe, [channel]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  String toString() => super.toString();
  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
          Invocation.method(#listenToReactiveValues, [reactiveValues]),
          returnValueForMissingStub: null);
  @override
  void addListener(void Function()? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(void Function()? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i8.NavigationService {
  @override
  String get previousRoute =>
      (super.noSuchMethod(Invocation.getter(#previousRoute), returnValue: '')
          as String);
  @override
  String get currentRoute =>
      (super.noSuchMethod(Invocation.getter(#currentRoute), returnValue: '')
          as String);
  @override
  _i9.GlobalKey<_i9.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(Invocation.method(#nestedNavigationKey, [index]))
          as _i9.GlobalKey<_i9.NavigatorState>?);
  @override
  void config(
          {bool? enableLog,
          bool? defaultPopGesture,
          bool? defaultOpaqueRoute,
          Duration? defaultDurationTransition,
          bool? defaultGlobalState,
          String? defaultTransition}) =>
      super.noSuchMethod(
          Invocation.method(#config, [], {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransition: defaultTransition
          }),
          returnValueForMissingStub: null);
  @override
  _i2.Future<T?>? navigateWithTransition<T>(_i9.Widget? page,
          {bool? opaque,
          String? transition = r'',
          Duration? duration,
          bool? popGesture,
          int? id,
          _i9.Curve? curve,
          _i8.Bindings? binding,
          bool? fullscreenDialog = false,
          bool? preventDuplicates = true,
          _i8.Transition? transitionClass}) =>
      (super.noSuchMethod(Invocation.method(#navigateWithTransition, [
        page
      ], {
        #opaque: opaque,
        #transition: transition,
        #duration: duration,
        #popGesture: popGesture,
        #id: id,
        #curve: curve,
        #binding: binding,
        #fullscreenDialog: fullscreenDialog,
        #preventDuplicates: preventDuplicates,
        #transitionClass: transitionClass
      })) as _i2.Future<T?>?);
  @override
  _i2.Future<T?>? replaceWithTransition<T>(_i9.Widget? page,
          {bool? opaque,
          String? transition = r'',
          Duration? duration,
          bool? popGesture,
          int? id,
          _i9.Curve? curve,
          _i8.Bindings? binding,
          bool? fullscreenDialog = false,
          bool? preventDuplicates = true,
          _i8.Transition? transitionClass}) =>
      (super.noSuchMethod(Invocation.method(#replaceWithTransition, [
        page
      ], {
        #opaque: opaque,
        #transition: transition,
        #duration: duration,
        #popGesture: popGesture,
        #id: id,
        #curve: curve,
        #binding: binding,
        #fullscreenDialog: fullscreenDialog,
        #preventDuplicates: preventDuplicates,
        #transitionClass: transitionClass
      })) as _i2.Future<T?>?);
  @override
  bool back<T>({T? result, int? id}) => (super.noSuchMethod(
      Invocation.method(#back, [], {#result: result, #id: id}),
      returnValue: false) as bool);
  @override
  void popUntil(_i9.RoutePredicate? predicate) =>
      super.noSuchMethod(Invocation.method(#popUntil, [predicate]),
          returnValueForMissingStub: null);
  @override
  void popRepeated(int? popTimes) =>
      super.noSuchMethod(Invocation.method(#popRepeated, [popTimes]),
          returnValueForMissingStub: null);
  @override
  _i2.Future<T?>? navigateTo<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#navigateTo, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i2.Future<T?>?);
  @override
  _i2.Future<T?>? navigateToView<T>(_i9.Widget? view,
          {dynamic arguments,
          int? id,
          bool? opaque,
          _i9.Curve? curve,
          _i8.Bindings? binding,
          Duration? duration,
          bool? fullscreenDialog = false,
          bool? popGesture,
          bool? preventDuplicates = true,
          _i8.Transition? transition}) =>
      (super.noSuchMethod(Invocation.method(#navigateToView, [
        view
      ], {
        #arguments: arguments,
        #id: id,
        #opaque: opaque,
        #curve: curve,
        #binding: binding,
        #duration: duration,
        #fullscreenDialog: fullscreenDialog,
        #popGesture: popGesture,
        #preventDuplicates: preventDuplicates,
        #transition: transition
      })) as _i2.Future<T?>?);
  @override
  _i2.Future<T?>? replaceWith<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#replaceWith, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i2.Future<T?>?);
  @override
  _i2.Future<T?>? clearStackAndShow<T>(String? routeName,
          {dynamic arguments, int? id, Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#clearStackAndShow, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #parameters: parameters
      })) as _i2.Future<T?>?);
  @override
  _i2.Future<T?>? clearTillFirstAndShow<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#clearTillFirstAndShow, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i2.Future<T?>?);
  @override
  _i2.Future<T?>? clearTillFirstAndShowView<T>(_i9.Widget? view,
          {dynamic arguments, int? id}) =>
      (super.noSuchMethod(Invocation.method(#clearTillFirstAndShowView, [view],
          {#arguments: arguments, #id: id})) as _i2.Future<T?>?);
  @override
  _i2.Future<T?>? pushNamedAndRemoveUntil<T>(String? routeName,
          {_i9.RoutePredicate? predicate, dynamic arguments, int? id}) =>
      (super.noSuchMethod(Invocation.method(#pushNamedAndRemoveUntil, [
        routeName
      ], {
        #predicate: predicate,
        #arguments: arguments,
        #id: id
      })) as _i2.Future<T?>?);
  @override
  String toString() => super.toString();
}

/// A class which mocks [StartupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartupService extends _i1.Mock implements _i10.StartupService {
  @override
  bool get hasLoggedInUser => (super
          .noSuchMethod(Invocation.getter(#hasLoggedInUser), returnValue: false)
      as bool);
  @override
  void checkIfUserSavedToDisk() =>
      super.noSuchMethod(Invocation.method(#checkIfUserSavedToDisk, []),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ZuriApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockZuriApiService extends _i1.Mock implements _i11.ZuriApiService {
  @override
  _i3.Dio get dio =>
      (super.noSuchMethod(Invocation.getter(#dio), returnValue: _FakeDio_1())
          as _i3.Dio);
  @override
  _i4.CacheOptions get cacheOptions =>
      (super.noSuchMethod(Invocation.getter(#cacheOptions),
          returnValue: _FakeCacheOptions_2()) as _i4.CacheOptions);
  @override
  _i2.Future<void> confirmEmail({String? otpCode}) => (super.noSuchMethod(
      Invocation.method(#confirmEmail, [], {#otpCode: otpCode}),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<dynamic> login({String? email, String? password}) =>
      (super.noSuchMethod(
          Invocation.method(#login, [], {#email: email, #password: password}),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<void> requestPasswordResetCode({String? email}) =>
      (super.noSuchMethod(
          Invocation.method(#requestPasswordResetCode, [], {#email: email}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<void> signup(
          {String? password, String? email, String? fName, String? lName}) =>
      (super.noSuchMethod(
          Invocation.method(#signup, [], {
            #password: password,
            #email: email,
            #fName: fName,
            #lName: lName
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<void> updateUserPassword({String? password, String? code}) =>
      (super.noSuchMethod(
          Invocation.method(
              #updateUserPassword, [], {#password: password, #code: code}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<void> verifyPasswordResetCode({String? resetCode}) =>
      (super.noSuchMethod(
          Invocation.method(
              #verifyPasswordResetCode, [], {#resetCode: resetCode}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<void> addLoggedInUserToOrganization(
          {String? organizationId, String? email, dynamic token}) =>
      (super.noSuchMethod(
          Invocation.method(#addLoggedInUserToOrganization, [],
              {#organizationId: organizationId, #email: email, #token: token}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<dynamic> invitePeopleToOrganization(
          {String? organizationId, List<String>? email, dynamic token}) =>
      (super.noSuchMethod(
          Invocation.method(#invitePeopleToOrganization, [],
              {#organizationId: organizationId, #email: email, #token: token}),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<Map<String, dynamic>> createOrganizationUsingEmail(
          {String? email, dynamic token}) =>
      (super.noSuchMethod(
              Invocation.method(#createOrganizationUsingEmail, [],
                  {#email: email, #token: token}),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<Map<String, dynamic>> fetchOrganizationDetails(
          {String? organizationId, dynamic token}) =>
      (super.noSuchMethod(
              Invocation.method(#fetchOrganizationDetails, [],
                  {#organizationId: organizationId, #token: token}),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<Map<String, dynamic>> fetchOrganizationsListFromRemote(
          {String? email, dynamic token}) =>
      (super.noSuchMethod(
              Invocation.method(#fetchOrganizationsListFromRemote, [],
                  {#email: email, #token: token}),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<dynamic> sendMessageToChannel(
          {dynamic channel_id,
          dynamic senderId,
          dynamic message,
          dynamic organization_id}) =>
      (super.noSuchMethod(
          Invocation.method(#sendMessageToChannel, [], {
            #channel_id: channel_id,
            #senderId: senderId,
            #message: message,
            #organization_id: organization_id
          }),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<String> fetchChannelSocketId(
          {String? channelId, String? organizationId, dynamic token}) =>
      (super.noSuchMethod(
          Invocation.method(#fetchChannelSocketId, [], {
            #channelId: channelId,
            #organizationId: organizationId,
            #token: token
          }),
          returnValue: Future<String>.value('')) as _i2.Future<String>);
  @override
  _i2.Future<dynamic> fetchChannelsListUsingOrgId(
          {String? organizationId, dynamic token}) =>
      (super.noSuchMethod(
          Invocation.method(#fetchChannelsListUsingOrgId, [],
              {#organizationId: organizationId, #token: token}),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> addUserToChannel(
          dynamic organizationId, dynamic channelId,
          {String? id,
          String? role_id,
          bool? is_admin,
          String? prop1,
          String? prop2,
          String? prop3}) =>
      (super.noSuchMethod(
          Invocation.method(#addUserToChannel, [
            organizationId,
            channelId
          ], {
            #id: id,
            #role_id: role_id,
            #is_admin: is_admin,
            #prop1: prop1,
            #prop2: prop2,
            #prop3: prop3
          }),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> createChannelsUsingOrgId(
          {dynamic sessionId,
          dynamic insertedOrganization,
          String? name,
          String? owner,
          String? description,
          bool? private,
          String? topic,
          bool? defaultChannel}) =>
      (super.noSuchMethod(
          Invocation.method(#createChannelsUsingOrgId, [], {
            #sessionId: sessionId,
            #insertedOrganization: insertedOrganization,
            #name: name,
            #owner: owner,
            #description: description,
            #private: private,
            #topic: topic,
            #defaultChannel: defaultChannel
          }),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> fetchChannelMessages(
          {String? channelId, String? organizationId}) =>
      (super.noSuchMethod(
          Invocation.method(#fetchChannelMessages, [],
              {#channelId: channelId, #organizationId: organizationId}),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<Map<String, dynamic>> sendMessageToDM(
          {dynamic roomId, dynamic senderId, dynamic message, dynamic orgId}) =>
      (super.noSuchMethod(
              Invocation.method(#sendMessageToDM, [], {
                #roomId: roomId,
                #senderId: senderId,
                #message: message,
                #orgId: orgId
              }),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<Map<String, dynamic>> markMessageAsRead(dynamic messageId) =>
      (super.noSuchMethod(Invocation.method(#markMessageAsRead, [messageId]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<Map<String, dynamic>> getRoomInfo({dynamic roomId}) => (super
          .noSuchMethod(Invocation.method(#getRoomInfo, [], {#roomId: roomId}),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
      as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<Map<String, dynamic>> fetchRoomMessages(
          {dynamic roomId, dynamic orgId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #fetchRoomMessages, [], {#roomId: roomId, #orgId: orgId}),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<Map<String, dynamic>> createRoom(
          {_i5.User? currentUser, _i5.Users? user, String? orgId}) =>
      (super.noSuchMethod(
              Invocation.method(#createRoom, [],
                  {#currentUser: currentUser, #user: user, #orgId: orgId}),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<Map<String, dynamic>> reactToMessage(
          {dynamic orgId,
          dynamic roomId,
          dynamic messageId,
          _i5.ReactToMessage? reactToMessage}) =>
      (super.noSuchMethod(
              Invocation.method(#reactToMessage, [], {
                #orgId: orgId,
                #roomId: roomId,
                #messageId: messageId,
                #reactToMessage: reactToMessage
              }),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<dynamic> fetchFileListUsingOrgId({String? orgId, dynamic token}) =>
      (super.noSuchMethod(
          Invocation.method(
              #fetchFileListUsingOrgId, [], {#orgId: orgId, #token: token}),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<List<_i5.Users>> fetchMemberListUsingOrgId(
          {String? organizationId, dynamic token}) =>
      (super.noSuchMethod(
              Invocation.method(#fetchMemberListUsingOrgId, [],
                  {#organizationId: organizationId, #token: token}),
              returnValue: Future<List<_i5.Users>>.value(<_i5.Users>[]))
          as _i2.Future<List<_i5.Users>>);
  @override
  _i2.Future<dynamic> fetchDMs({dynamic orgId, dynamic userId}) =>
      (super.noSuchMethod(
          Invocation.method(#fetchDMs, [], {#orgId: orgId, #userId: userId}),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<Map<String, dynamic>> getUserProfile(
          {dynamic orgId, dynamic memberId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getUserProfile, [], {#orgId: orgId, #memberId: memberId}),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<_i5.Member> fetchMemberDetail(
          {String? organizationId, String? memberId, String? token}) =>
      (super.noSuchMethod(
              Invocation.method(#fetchMemberDetail, [], {
                #organizationId: organizationId,
                #memberId: memberId,
                #token: token
              }),
              returnValue: Future<_i5.Member>.value(_FakeMember_3()))
          as _i2.Future<_i5.Member>);
  @override
  _i2.Future<Map<String, dynamic>> getMemberDetails(
          {String? organizationId, String? memberId, String? token}) =>
      (super.noSuchMethod(
              Invocation.method(#getMemberDetails, [], {
                #organizationId: organizationId,
                #memberId: memberId,
                #token: token
              }),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<_i5.User> fetchUserDetail({String? userId}) => (super.noSuchMethod(
          Invocation.method(#fetchUserDetail, [], {#userId: userId}),
          returnValue: Future<_i5.User>.value(_FakeUser_4()))
      as _i2.Future<_i5.User>);
  @override
  _i2.Future<Map<String, dynamic>> getUserDetails({String? userId}) => (super
      .noSuchMethod(Invocation.method(#getUserDetails, [], {#userId: userId}),
          returnValue:
              Future<Map<String, dynamic>>.value(<String, dynamic>{})) as _i2
      .Future<Map<String, dynamic>>);
  @override
  _i2.Future<void> updateUserDetails(
          {String? organizationId,
          String? memberId,
          dynamic token,
          String? bio,
          String? displayName,
          String? firstName,
          String? lastName,
          String? phoneNumber,
          String? pronoun,
          String? timeZone}) =>
      (super.noSuchMethod(
          Invocation.method(#updateUserDetails, [], {
            #organizationId: organizationId,
            #memberId: memberId,
            #token: token,
            #bio: bio,
            #displayName: displayName,
            #firstName: firstName,
            #lastName: lastName,
            #phoneNumber: phoneNumber,
            #pronoun: pronoun,
            #timeZone: timeZone
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<List<_i5.Todo>> fetchTodoList() =>
      (super.noSuchMethod(Invocation.method(#fetchTodoList, []),
              returnValue: Future<List<_i5.Todo>>.value(<_i5.Todo>[]))
          as _i2.Future<List<_i5.Todo>>);
  @override
  _i2.Future<void> createTodo(_i5.Todo? todo, String? token) =>
      (super.noSuchMethod(Invocation.method(#createTodo, [todo, token]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<void> signOut(String? token) =>
      (super.noSuchMethod(Invocation.method(#signOut, [token]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<dynamic> removeUserFromChannel(
          {dynamic organizationId, dynamic channelId, dynamic memberId}) =>
      (super.noSuchMethod(
          Invocation.method(#removeUserFromChannel, [], {
            #organizationId: organizationId,
            #channelId: channelId,
            #memberId: memberId
          }),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<Map<String, dynamic>> UpdateUserDetails(
          {dynamic organizationId,
          dynamic memberId,
          dynamic token,
          String? bio,
          String? displayName,
          String? firstName,
          String? lastName,
          String? phoneNumber,
          String? pronoun,
          String? timeZone}) =>
      (super.noSuchMethod(
              Invocation.method(#UpdateUserDetails, [], {
                #organizationId: organizationId,
                #memberId: memberId,
                #token: token,
                #bio: bio,
                #displayName: displayName,
                #firstName: firstName,
                #lastName: lastName,
                #phoneNumber: phoneNumber,
                #pronoun: pronoun,
                #timeZone: timeZone
              }),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<Map<String, dynamic>> UpdateUserPicture(
          {dynamic organizationId,
          dynamic memberId,
          dynamic token,
          _i12.File? img}) =>
      (super.noSuchMethod(
              Invocation.method(#UpdateUserPicture, [], {
                #organizationId: organizationId,
                #memberId: memberId,
                #token: token,
                #img: img
              }),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<_i5.Member> patchProfilePicture(
          {String? organizationId, String? memberId, String? token}) =>
      (super.noSuchMethod(
              Invocation.method(#patchProfilePicture, [], {
                #organizationId: organizationId,
                #memberId: memberId,
                #token: token
              }),
              returnValue: Future<_i5.Member>.value(_FakeMember_3()))
          as _i2.Future<_i5.Member>);
  @override
  _i2.Future<Map<String, dynamic>> deleteOrganization(
          {String? organizationId, dynamic token}) =>
      (super.noSuchMethod(
              Invocation.method(#deleteOrganization, [],
                  {#organizationId: organizationId, #token: token}),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<Map<String, dynamic>> fetchPinnedMessgaes(
          dynamic roomId, dynamic orgId) =>
      (super.noSuchMethod(
              Invocation.method(#fetchPinnedMessgaes, [roomId, orgId]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<Map<String, dynamic>> pinMessage(
          dynamic messageId, dynamic orgId) =>
      (super.noSuchMethod(Invocation.method(#pinMessage, [messageId, orgId]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<Map<String, dynamic>> updateOrganizationDetails(
          {String? organizationId, dynamic token, String? url, String? name}) =>
      (super.noSuchMethod(
              Invocation.method(#updateOrganizationDetails, [], {
                #organizationId: organizationId,
                #token: token,
                #url: url,
                #name: name
              }),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<Map<String, dynamic>> updateOrganizationName(
          {String? name, String? organizationId, String? token}) =>
      (super.noSuchMethod(
              Invocation.method(#updateOrganizationName, [], {
                #name: name,
                #organizationId: organizationId,
                #token: token
              }),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<Map<String, dynamic>> updateOrganizationUrl(
          {String? url, String? organizationId, String? token}) =>
      (super.noSuchMethod(
              Invocation.method(#updateOrganizationUrl, [],
                  {#url: url, #organizationId: organizationId, #token: token}),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i2.Future<Map<String, dynamic>>);
  @override
  _i2.Future<dynamic> updateUserDetail(
          {String? organizationId,
          String? memberId,
          String? token,
          String? bio,
          String? displayName,
          String? lastName,
          String? firstName,
          String? phoneNumber,
          String? pronoun}) =>
      (super.noSuchMethod(
          Invocation.method(#updateUserDetail, [], {
            #organizationId: organizationId,
            #memberId: memberId,
            #token: token,
            #bio: bio,
            #displayName: displayName,
            #lastName: lastName,
            #firstName: firstName,
            #phoneNumber: phoneNumber,
            #pronoun: pronoun
          }),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> updateUserPicture(
          {dynamic organizationId,
          dynamic memberId,
          dynamic token,
          _i12.File? url}) =>
      (super.noSuchMethod(
          Invocation.method(#updateUserPicture, [], {
            #organizationId: organizationId,
            #memberId: memberId,
            #token: token,
            #url: url
          }),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ChannelsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannelsService extends _i1.Mock implements _i13.ChannelsService {
  @override
  String get selectedCreatedOrganisationId =>
      (super.noSuchMethod(Invocation.getter(#selectedCreatedOrganisationId),
          returnValue: '') as String);
  @override
  void setUser(_i5.Users? user) =>
      super.noSuchMethod(Invocation.method(#setUser, [user]),
          returnValueForMissingStub: null);
  @override
  _i2.Future<_i5.Users> getUser() =>
      (super.noSuchMethod(Invocation.method(#getUser, []),
              returnValue: Future<_i5.Users>.value(_FakeUsers_5()))
          as _i2.Future<_i5.Users>);
  @override
  void saveChannelId(String? channelId) =>
      super.noSuchMethod(Invocation.method(#saveChannelId, [channelId]),
          returnValueForMissingStub: null);
  @override
  String getChannelId() =>
      (super.noSuchMethod(Invocation.method(#getChannelId, []), returnValue: '')
          as String);
  @override
  void saveChannelList(List<_i5.Channel>? channels) =>
      super.noSuchMethod(Invocation.method(#saveChannelList, [channels]),
          returnValueForMissingStub: null);
  @override
  List<_i5.Channel> getChannelList() =>
      (super.noSuchMethod(Invocation.method(#getChannelList, []),
          returnValue: <_i5.Channel>[]) as List<_i5.Channel>);
  @override
  void setChannel(_i5.Channel? channel) =>
      super.noSuchMethod(Invocation.method(#setChannel, [channel]),
          returnValueForMissingStub: null);
  @override
  _i5.Channel getChannel() =>
      (super.noSuchMethod(Invocation.method(#getChannel, []),
          returnValue: _FakeChannel_6()) as _i5.Channel);
  @override
  _i2.Future<List<_i5.Channel>> getChannels({String? organizationId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getChannels, [], {#organizationId: organizationId}),
              returnValue: Future<List<_i5.Channel>>.value(<_i5.Channel>[]))
          as _i2.Future<List<_i5.Channel>>);
  @override
  _i2.Future<_i5.Channel> createChannels(
          {String? name,
          String? owner,
          String? description,
          bool? private,
          String? topic,
          bool? defaultChannel}) =>
      (super.noSuchMethod(
              Invocation.method(#createChannels, [], {
                #name: name,
                #owner: owner,
                #description: description,
                #private: private,
                #topic: topic,
                #defaultChannel: defaultChannel
              }),
              returnValue: Future<_i5.Channel>.value(_FakeChannel_6()))
          as _i2.Future<_i5.Channel>);
  @override
  _i2.Future<void> addUserToChannel(
          {String? id,
          String? role_id,
          bool? is_admin,
          String? prop1,
          String? prop2,
          String? prop3}) =>
      (super.noSuchMethod(
          Invocation.method(#addUserToChannel, [], {
            #id: id,
            #role_id: role_id,
            #is_admin: is_admin,
            #prop1: prop1,
            #prop2: prop2,
            #prop3: prop3
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<void> handleRemoveUserFromChannel(
          {String? channel_id, String? member_id}) =>
      (super.noSuchMethod(
          Invocation.method(#handleRemoveUserFromChannel, [],
              {#channel_id: channel_id, #member_id: member_id}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<dynamic> sendMessage(
          {dynamic channel_id,
          dynamic senderId,
          dynamic message,
          dynamic org_id}) =>
      (super.noSuchMethod(
          Invocation.method(#sendMessage, [], {
            #channel_id: channel_id,
            #senderId: senderId,
            #message: message,
            #org_id: org_id
          }),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<List<_i5.ChannelMessage>> fetchChannelMessages(
          String? channelId) =>
      (super.noSuchMethod(Invocation.method(#fetchChannelMessages, [channelId]),
          returnValue: Future<List<_i5.ChannelMessage>>.value(
              <_i5.ChannelMessage>[])) as _i2.Future<List<_i5.ChannelMessage>>);
  @override
  _i2.Future<String> fetchChannelSocketId() =>
      (super.noSuchMethod(Invocation.method(#fetchChannelSocketId, []),
          returnValue: Future<String>.value('')) as _i2.Future<String>);
  @override
  String toString() => super.toString();
  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
          Invocation.method(#listenToReactiveValues, [reactiveValues]),
          returnValueForMissingStub: null);
  @override
  void addListener(void Function()? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(void Function()? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [DMService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDMService extends _i1.Mock implements _i14.DMService {
  @override
  void setUser(_i5.Users? user) =>
      super.noSuchMethod(Invocation.method(#setUser, [user]),
          returnValueForMissingStub: null);
  @override
  _i2.Future<_i5.Users> getUser() =>
      (super.noSuchMethod(Invocation.method(#getUser, []),
              returnValue: Future<_i5.Users>.value(_FakeUsers_5()))
          as _i2.Future<_i5.Users>);
  @override
  void setExistingRoomInfo(_i5.DM? dm) =>
      super.noSuchMethod(Invocation.method(#setExistingRoomInfo, [dm]),
          returnValueForMissingStub: null);
  @override
  _i2.Future<void> setNewRoomInfo(_i5.Users? user) =>
      (super.noSuchMethod(Invocation.method(#setNewRoomInfo, [user]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<_i5.SendMessageResponse> sendMessage(
          dynamic roomId, dynamic senderId, dynamic message) =>
      (super.noSuchMethod(
              Invocation.method(#sendMessage, [roomId, senderId, message]),
              returnValue: Future<_i5.SendMessageResponse>.value(
                  _FakeSendMessageResponse_7()))
          as _i2.Future<_i5.SendMessageResponse>);
  @override
  _i2.Future<String> createRoom(_i5.User? currentUser, _i5.Users? user) =>
      (super.noSuchMethod(Invocation.method(#createRoom, [currentUser, user]),
          returnValue: Future<String>.value('')) as _i2.Future<String>);
  @override
  _i2.Future<_i5.DM?> getRoomInfo(dynamic roomId) =>
      (super.noSuchMethod(Invocation.method(#getRoomInfo, [roomId]),
          returnValue: Future<_i5.DM?>.value()) as _i2.Future<_i5.DM?>);
  @override
  _i2.Future<List<_i5.DMRoomsResponse>> getDMs(dynamic orgId) =>
      (super.noSuchMethod(Invocation.method(#getDMs, [orgId]),
              returnValue: Future<List<_i5.DMRoomsResponse>>.value(
                  <_i5.DMRoomsResponse>[]))
          as _i2.Future<List<_i5.DMRoomsResponse>>);
  @override
  _i2.Future<List<_i5.Results>> fetchRoomMessages(dynamic roomId) =>
      (super.noSuchMethod(Invocation.method(#fetchRoomMessages, [roomId]),
              returnValue: Future<List<_i5.Results>>.value(<_i5.Results>[]))
          as _i2.Future<List<_i5.Results>>);
  @override
  _i2.Future<void> markMessageAsRead(dynamic messageId) =>
      (super.noSuchMethod(Invocation.method(#markMessageAsRead, [messageId]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<void> reactToMessage(dynamic roomId, dynamic messageId,
          _i5.ReactToMessage? reactToMessage) =>
      (super.noSuchMethod(
          Invocation.method(
              #reactToMessage, [roomId, messageId, reactToMessage]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<String> fetchChannelSocketId(dynamic roomId) =>
      (super.noSuchMethod(Invocation.method(#fetchChannelSocketId, [roomId]),
          returnValue: Future<String>.value('')) as _i2.Future<String>);
  @override
  _i2.Future<List<_i5.Users>> fetchAllUsersForDm() =>
      (super.noSuchMethod(Invocation.method(#fetchAllUsersForDm, []),
              returnValue: Future<List<_i5.Users>>.value(<_i5.Users>[]))
          as _i2.Future<List<_i5.Users>>);
  @override
  _i2.Future<void> pinMessage(String? messageId) =>
      (super.noSuchMethod(Invocation.method(#pinMessage, [messageId]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<List<String>> fetchPinnedMessages(String? roomId) =>
      (super.noSuchMethod(Invocation.method(#fetchPinnedMessages, [roomId]),
              returnValue: Future<List<String>>.value(<String>[]))
          as _i2.Future<List<String>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i15.LocalStorageService {
  @override
  void setAuthResponse(_i5.AuthResponse? authResponseToSave) => super
      .noSuchMethod(Invocation.method(#setAuthResponse, [authResponseToSave]),
          returnValueForMissingStub: null);
  @override
  void removeAuthResponse() =>
      super.noSuchMethod(Invocation.method(#removeAuthResponse, []),
          returnValueForMissingStub: null);
  @override
  void setAccessibility(_i5.Accessibility? accessibilityResponseToSave) =>
      super.noSuchMethod(
          Invocation.method(#setAccessibility, [accessibilityResponseToSave]),
          returnValueForMissingStub: null);
  @override
  void setAdvanced(_i5.Advanced? advanced) =>
      super.noSuchMethod(Invocation.method(#setAdvanced, [advanced]),
          returnValueForMissingStub: null);
  @override
  void setAudioAndVideo(_i5.AudioAndVideo? audioAndVideo) =>
      super.noSuchMethod(Invocation.method(#setAudioAndVideo, [audioAndVideo]),
          returnValueForMissingStub: null);
  @override
  void setMessagesAndMedia(_i5.MessagesAndMedia? media) =>
      super.noSuchMethod(Invocation.method(#setMessagesAndMedia, [media]),
          returnValueForMissingStub: null);
  @override
  void setNotification(_i5.Notifications? notification) =>
      super.noSuchMethod(Invocation.method(#setNotification, [notification]),
          returnValueForMissingStub: null);
  @override
  void setSideBar(_i5.SideBar? sideBar) =>
      super.noSuchMethod(Invocation.method(#setSideBar, [sideBar]),
          returnValueForMissingStub: null);
  @override
  void setThemes(_i5.Themes? themes) =>
      super.noSuchMethod(Invocation.method(#setThemes, [themes]),
          returnValueForMissingStub: null);
  @override
  _i2.Future<void> saveToDisk<T>(String? key, T? content) =>
      (super.noSuchMethod(Invocation.method(#saveToDisk, [key, content]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  Object? getFromDisk(String? key) =>
      (super.noSuchMethod(Invocation.method(#getFromDisk, [key])) as Object?);
  @override
  _i2.Future<bool> removeFromDisk(String? key) =>
      (super.noSuchMethod(Invocation.method(#removeFromDisk, [key]),
          returnValue: Future<bool>.value(false)) as _i2.Future<bool>);
  @override
  void setOrganizationResponse(
          _i5.OrganizationResponse? organizationResponseToSave) =>
      super.noSuchMethod(
          Invocation.method(
              #setOrganizationResponse, [organizationResponseToSave]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [OrganizationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrganizationService extends _i1.Mock
    implements _i16.OrganizationService {
  @override
  set organization(_i5.Organization? _organization) =>
      super.noSuchMethod(Invocation.setter(#organization, _organization),
          returnValueForMissingStub: null);
  @override
  _i5.Auth get auth =>
      (super.noSuchMethod(Invocation.getter(#auth), returnValue: _FakeAuth_8())
          as _i5.Auth);
  @override
  List<_i5.DM> get dm =>
      (super.noSuchMethod(Invocation.getter(#dm), returnValue: <_i5.DM>[])
          as List<_i5.DM>);
  @override
  int get selectedOrganization =>
      (super.noSuchMethod(Invocation.getter(#selectedOrganization),
          returnValue: 0) as int);
  @override
  void setDms(List<_i5.DM>? dm) =>
      super.noSuchMethod(Invocation.method(#setDms, [dm]),
          returnValueForMissingStub: null);
  @override
  void saveOrganizationId(String? orgId) =>
      super.noSuchMethod(Invocation.method(#saveOrganizationId, [orgId]),
          returnValueForMissingStub: null);
  @override
  void saveMemberId(String? memId) =>
      super.noSuchMethod(Invocation.method(#saveMemberId, [memId]),
          returnValueForMissingStub: null);
  @override
  _i2.Future<void> updateOrganizationUrl({String? url, String? token}) =>
      (super.noSuchMethod(
          Invocation.method(
              #updateOrganizationUrl, [], {#url: url, #token: token}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<void> updateOrganizationName({String? name, String? token}) =>
      (super.noSuchMethod(
          Invocation.method(
              #updateOrganizationName, [], {#name: name, #token: token}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  String getOrganizationId() =>
      (super.noSuchMethod(Invocation.method(#getOrganizationId, []),
          returnValue: '') as String);
  @override
  String getMemberId() =>
      (super.noSuchMethod(Invocation.method(#getMemberId, []), returnValue: '')
          as String);
  @override
  void changeSelectedOrganization(int? index) => super.noSuchMethod(
      Invocation.method(#changeSelectedOrganization, [index]),
      returnValueForMissingStub: null);
  @override
  _i2.Future<List<_i5.Organization>> getOrganizations() =>
      (super.noSuchMethod(Invocation.method(#getOrganizations, []),
              returnValue:
                  Future<List<_i5.Organization>>.value(<_i5.Organization>[]))
          as _i2.Future<List<_i5.Organization>>);
  @override
  _i2.Future<void> addMemberToOrganization(String? organizationId,
          {String? email, String? token}) =>
      (super.noSuchMethod(
          Invocation.method(#addMemberToOrganization, [organizationId],
              {#email: email, #token: token}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<dynamic> invitePeopleToOrganization(
          String? organizationId, List<String>? email) =>
      (super.noSuchMethod(
          Invocation.method(
              #invitePeopleToOrganization, [organizationId, email]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<List<_i5.Users>> fetchMemberListUsingOrgId(
          String? organizationId, String? token) =>
      (super.noSuchMethod(
              Invocation.method(
                  #fetchMemberListUsingOrgId, [organizationId, token]),
              returnValue: Future<List<_i5.Users>>.value(<_i5.Users>[]))
          as _i2.Future<List<_i5.Users>>);
  @override
  _i2.Future<void> createOrganization(String? email) =>
      (super.noSuchMethod(Invocation.method(#createOrganization, [email]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  List<_i5.Organization> getUserSelectedOrganisations() =>
      (super.noSuchMethod(Invocation.method(#getUserSelectedOrganisations, []),
          returnValue: <_i5.Organization>[]) as List<_i5.Organization>);
  @override
  _i2.Future<void> saveUserSelectedOrganizations(
          List<_i5.Organization>? organizations) =>
      (super.noSuchMethod(
          Invocation.method(#saveUserSelectedOrganizations, [organizations]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<_i5.UserProfile> getUserProfile(
          String? organizationId, String? memberId) =>
      (super.noSuchMethod(
              Invocation.method(#getUserProfile, [organizationId, memberId]),
              returnValue: Future<_i5.UserProfile>.value(_FakeUserProfile_9()))
          as _i2.Future<_i5.UserProfile>);
  @override
  _i2.Future<void> updateUser(
          {String? bio,
          String? displayName,
          String? firstName,
          String? lastName,
          String? phoneNumber,
          String? pronoun}) =>
      (super.noSuchMethod(
          Invocation.method(#updateUser, [], {
            #bio: bio,
            #displayName: displayName,
            #firstName: firstName,
            #lastName: lastName,
            #phoneNumber: phoneNumber,
            #pronoun: pronoun
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<void> updateUserImage({String? token, _i12.File? url}) =>
      (super.noSuchMethod(
          Invocation.method(#updateUserImage, [], {#token: token, #url: url}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [RecentSearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecentSearchService extends _i1.Mock
    implements _i17.RecentSearchService {
  @override
  _i2.Future<void> setRecentSearch(String? query) =>
      (super.noSuchMethod(Invocation.method(#setRecentSearch, [query]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<List<String>> getRecentSearch() =>
      (super.noSuchMethod(Invocation.method(#getRecentSearch, []),
              returnValue: Future<List<String>>.value(<String>[]))
          as _i2.Future<List<String>>);
  @override
  _i2.Future<void> destroyRecentSearch() =>
      (super.noSuchMethod(Invocation.method(#destroyRecentSearch, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i18.UserService {
  @override
  _i5.Auth get auth =>
      (super.noSuchMethod(Invocation.getter(#auth), returnValue: _FakeAuth_8())
          as _i5.Auth);
  @override
  _i5.Organization get organization =>
      (super.noSuchMethod(Invocation.getter(#organization),
          returnValue: _FakeOrganization_10()) as _i5.Organization);
  @override
  String getUserId() =>
      (super.noSuchMethod(Invocation.method(#getUserId, []), returnValue: '')
          as String);
  @override
  _i2.Future<void> fetchMemberDetails(String? displayName) =>
      (super.noSuchMethod(Invocation.method(#fetchMemberDetails, [displayName]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  _i2.Future<void> getmember() =>
      (super.noSuchMethod(Invocation.method(#getmember, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [WindowTitleBarService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWindowTitleBarService extends _i1.Mock
    implements _i19.WindowTitleBarService {
  @override
  bool get IsHome =>
      (super.noSuchMethod(Invocation.getter(#IsHome), returnValue: false)
          as bool);
  @override
  String get Title =>
      (super.noSuchMethod(Invocation.getter(#Title), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  void setHome(bool? value) =>
      super.noSuchMethod(Invocation.method(#setHome, [value]),
          returnValueForMissingStub: null);
  @override
  void setTitle(String? value) =>
      super.noSuchMethod(Invocation.method(#setTitle, [value]),
          returnValueForMissingStub: null);
  @override
  void addListener(_i20.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i20.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
